### ISSUE TITLE
基于WIN11的LINUX子系统安装CLIP报错

### ISSUE THREAD

**Issue by billhuang6277** [jina-ai/clip-as-service#895] opened 2023-03-01 02:24 UTC
**Describe the bug**

![45c1417755ef8a200329a2b91d972b8](https://user-images.githubusercontent.com/102899726/222028994-d99bfe02-ae34-43de-8097-dc5b20197af4.jpg)

**Describe how you solve it**

---

**Environment**

**Screenshots**

**Comment by numb3r3** [comment] 2023-03-01 10:43
Thanks for pointing it out. I guess this is due to the upstream issue. We need some time to reproduce this issue.

**Comment by ZiniuYu** [comment] 2023-03-02 07:19
@billhuang6277 can you paste the full error trace? Thanks

**Comment by ZiniuYu** [comment] 2023-03-02 17:55
@billhuang6277 
I created a fresh python 3.10 env in win11 WSL ubuntu20, but was not able to reproduce your problem.
Could you provide more details? For example, what's your output of `jina -vf` and what's your `clip_server` version? Anything that may help use to reproduce the problem is welcomed.
Can you please also try again with `export JINA_LOG_LEVEL=DEBUG`?

```
(py310) ziniu@SurfaceBook:/mnt/c/Users/ziniu$ export JINA_LOG_LEVEL=debug
(py310) ziniu@SurfaceBook:/mnt/c/Users/ziniu$ python -m clip_server
DeprecationWarning: There is no current event loop (raised from /home/ziniu/miniconda3/envs/py310/lib/python3.10/site-packages/jina/orchestrate/flow/base.py:1892)
⠙ Waiting clip_t gateway... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0/2 0:00:00DEBUG  gateway/rep-0@76 adding connection for deployment clip_t/heads/0 to grpc://0.0.0.0:56397      [03/03/23 01:22:43]
DEBUG  gateway/rep-0@76 start server bound to 0.0.0.0:51000
DEBUG  gateway/rep-0@76 Running GatewayRuntime warmup
DEBUG  gateway/rep-0@76 starting warmup task for deployment clip_t
DEBUG  gateway/rep-0@65 ready and listening                                                          [03/03/23 01:22:43]⠼ Waiting clip_t... ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 1/2 0:00:05UserWarning: `docs` annotation must be a type hint, got DocumentArray instead, you should maybe remove the string annotation. Default valueDocumentArray will be used instead. (raised from /home/ziniu/miniconda3/envs/py310/lib/python3.10/site-packages/jina/serve/executors/__init__.py:119)  ViT-B-32.pt 25.9% • 91.5/354.0 MB • 204.8 kB/s • 0:21:22
                                                          DEBUG  gateway/rep-0@76 completed warmup task in 300.112263202  ViT-B-32.pt 100.0% • 354.0/354.0 MB • 252.7 kB/s • 0:00:00

⠋ Waiting clip_t... ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 1/2 0:19:45DEBUG  clip_t/rep-0@75 <clip_server.executors.clip_torch.CLIPEncoder object at 0x7f4aa9d61300> is    [03/03/23 01:42:29]
       successfully loaded!
DEBUG  clip_t/rep-0@75 start listening on 0.0.0.0:56397
DEBUG  clip_t/rep-0@75 run grpc server forever
DEBUG  clip_t/rep-0@65 ready and listening                                                           [03/03/23 01:42:29]
────────────────────────────────────────────── 🎉 Flow is ready to serve! ──────────────────────────────────────────────
╭────────────── 🔗 Endpoint ───────────────╮
│  ⛓      Protocol                   GRPC  │
│  🏠        Local          0.0.0.0:51000  │
│  🔒      Private    172.18.64.108:51000  │
╰──────────────────────────────────────────╯
DEBUG  Flow@65 2 Deployments (i.e. 2 Pods) are running in this Flow                                  [03/03/23 01:42:31]
Do you love Open Source? Help us get better and be heard in just 1 minute and 30 seconds 💖Your feedback will help us
build better features for Jina, your loved open-source project 🎉
Take the Jina user survey!
```

**Comment by billhuang6277** [comment] 2023-03-06 03:22
你好，


&nbsp; 可能是WIN11下LINUX子系统不够稳定导致的，我更换成VM环境,重新装LINUX，目前问题已经解决了。






娜美智能
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jina-ai/clip-as-service"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月2日(星期四) 下午3:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jina-ai/clip-as-service] 基于WIN11的LINUX子系统安装CLIP报错 (Issue #895)





 
@billhuang6277 can you paste the full error trace? Thanks

**Comment by ZiniuYu** [comment] 2023-03-06 03:32
Great news! It looks like you were able to fix the issue on your own. We appreciate your initiative and effort in resolving this problem. As a result, we're going to close this ticket. If you run into any more issues or have any other feedback, please don't hesitate to let us know. Thank you for your contribution!

**Closed by ZiniuYu** 2023-03-06 03:32 UTC
